services:
  builder:
    image: $registry/$tenant_name/comfyui-serverless:builder
    build:
      context: .
      target: builder
      args:
      - BASE_URL=$registry
  comfyui-serverless:
    image: $registry/$tenant_name/comfyui-serverless:comfyui
    build:
      context: .
      target: comfyui
      args:
      - BASE_URL=$registry

