name: 打包插件并发布到Releases

# 检测只有主分支的push操作会触发该工作流
on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发该工作流

jobs:
  build:
    name: 打包工作
    runs-on: ubuntu-latest

    steps:
      - name: 克隆代码
        uses: actions/checkout@v4
        with:
          ref: main # 指定主分支

      - name: 指定Node.js版本
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 指定 Node.js 20 版本

      - name: 安装pnpm
        run: npm install -g pnpm@latest

      - name: 安装依赖
        run: |
          cd chrome-extension
          pnpm install

      - name: 打包插件
        run: |
          cd chrome-extension  
          pnpm run build

      - name: 创建谷歌浏览器扩展zip文件
        run: |
          cd chrome-extension
          zip -r ../chrome-extension.zip ./dist

      - name: 创建serverless模版zip文件
        run: |
          zip -r ./serverless-template.zip ./serverless-template

      - name: 获取新版本号
        id: get_chrome_extension_version
        run: |
          # 尝试从 package.json 中获取版本号
          VERSION=$(node -p "require('./chrome-extension/package.json').version" 2>/dev/null || echo "v0.0.1")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New version:${VERSION}"

      - name: 创建Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./chrome-extension.zip
            ./serverless-template.zip
